### ISSUE TITLE
Mount familiar not working (in v10 gridded)

### ISSUE THREAD

**Issue by dineshm72** [Saibot393/Rideable#16]
Clicking the hotkey for it just silently fails to do anything.

To be honest, I'm not exactly sure what it's supposed to be doing differently from any normal mount anyway.  Is it the same as other mounting, only you're supposed to be putting it in the top corner rather than the center?  Are you doing some checking to ensure that only "familiars" can do it, if so how is that defined?  Is it based on size or size differential?

using v10.291, 2.2.1, and 2.0.1

**Comment by Saibot393** [comment]
There was another bug in the code related to the v2.0.0 update, will be fixed in v2.1.0.

The function is meant as an easy way to let familairs follow their master, without having to remember dragging them together with your character when you move.
Familiars are simply defined as tokens smaller than their master in at least on dimension (except in the PF2e system where a custom familiar token type exists).

**Comment by Saibot393** [comment]
The bug has been fixed in v2.1.0
