### ISSUE TITLE
When copying tokens and their riders from one scene to another, the riding tokens are "disconnected' from the ridden token, but still elevated.

### ISSUE THREAD

**Issue by devteamplus** [Saibot393/Rideable#25]
I have several characters on horseback.  They work fine in a scene.  If I select, copy, and then paste them into another scene, they appear properly.  However, the "riding" tokens are all now disconnected from the "ridden" token.  Yet, the riding tokens are all still elevated.

The only option I've found is to select the riding tokens, dismount them, then remount them onto their horses - or whatever they're riding.

Rideable v2.6.0
Foundry 11.307
Browser - Latest Chrome

**Comment by Saibot393** [comment]
This behaviour is due to the way i save the relation between riders ans ridden tokens and the way foundry saves ids. I might be able to implement a way for this to work properly but it will take a bit of time. For now there are two work arounds that could be usefull depending on your use case: 
1. You can set mounts to always spawn with a certain rider by entering the riders ID or name into the ridden tokens "Spawn riders" field.
2. You can teleport tokens across scenes by using the stairways module, which will keep the relation between rider and ridden token

**Comment by GambetTV** [comment]
One other bug with this is that if you use a "Toggle Mount" command instead of the separated "Mount" and "Unmount" commands, it will not unmount/remount the token from the mount on copy/pasted tokens.

**Comment by Saibot393** [comment]
To clarify: Did you have Token A mounted to Token B and then copy Token B upon which Token A is now mounted to the copy of Token B and cant be unmounted?

**Comment by GambetTV** [comment]
Yes, A is mounted on B, then I copy and paste both of them onto another scene. Token A is now dismounted, but I cannot remount it. The only way for me to do so so far is to hit the "Unmount" key, and then the "Mount" key, which seems to fix the problem. However, your newly added control that allows me to toggle between mount/unmount with a single keypress does not do the same thing. I had removed the "Unmount" and "Mount" controls to give me more hotkeys for other modules, and wanted to do it all with the toggle, but right now this does not work.

**Comment by Saibot393** [comment]
In my tests the toggle seems to work to unmount the token in the situation you described, though only when the copy of the ridden token is not hovered/selected.

**Comment by GambetTV** [comment]
Ah, you are right. Although it is a bit unintuitive, that you can't unmount a token you're hovering/targeting. Not sure if there's anything you can do about that, though. Anyway, thank you!

**Comment by Saibot393** [comment]
The problem by hovering the copy of the ridden token and since the selected token is still considered a riding token the programm tries to unmount the selected token from the hovered token, which fails since the "riding link" has been broken by the copy so nothing happens. 
I am however currently working on a way automatically copy all riding tokens when copying a ridden token, which should trivialize this problem anyway.

**Comment by Saibot393** [comment]
I have just released v2.9.0 which adds the ability to copy paste ridden tokens including their riders
