### ISSUE TITLE
Custom Convenient Effects not appearing as expected upon mounting

### ISSUE THREAD

**Issue by T-Whiz** [Saibot393/Rideable#35]
Thank you for providing this great module, it is really appreciated and is working great, except for a below issue I’ve encountered with custom Convenient Effects. My use case is attempting to set up some effects related to the dnd5e Mounted Combatant feat for one of my players.

**Expected**: When mounting a token with ‘DFreds Convenient Effects integration’ checked, the corresponding Convenient Effect is automatically added to the rider based on the effect name(s) in the Rideable and/or token settings. If a custom Convenient Effect has the same name as an existing Convenient Effect, then the first one in the Custom list is used instead of the standard effect.

**Actual**: As expected for the existing Convenient Effects (the effects provided by the CE module by default). For any other Custom effects added to Convenient Effects list, the effect isn’t applied. If a custom effect is added with the same name as one of the default effects, the default effect is applied instead of the custom version (for example if a Custom version of an effect is added with different settings or effects in the Effects tab).

Attached screen shots of example and settings details. I didn’t attach a log file because the console log doesn’t display any messages during mounting/unmounting for the custom effects.

**Steps to recreate**:

1. Select the hand icon on the left to open DFred’s Convenient Effects.
2. Select Create Effect to add a new custom effect with the name ‘Riding’.
3. Select Create Effect to add a new custom effect with the name ‘Prone’ (with no effects added to the Effects tab).
4. Open the Rideable settings and add ‘Riding’ in the ‘Custom riding effects’ field, then select Save Changes.
5. Import a Starter Hero from the system Starter Heroes compendium and a medium size or larger monster from the system Monsters (SRD) compendium.
6. Select the monster in the sidebar and view the Prototype Token settings to verify the ‘Token is Rideable’ setting is checked.
7. Add the PC and monster from the sidebar to the active scene.
8. Select and move the PC token onto the monster token or press M with the cursor over the monster token.
9. Repeat steps 4-8 except using ‘Prone’ in the Custom Riding effects field.
[Rideable-screen-shots-0923.pdf](https://github.com/Saibot393/Rideable/files/12623079/Rideable-screen-shots-0923.pdf)

**Comment by Saibot393** [comment]
Thanks for the detailed bug report. There was a bug with applying custom effects with DFreds CE which is fixed with the new v2.9.4.
However, when applying custom effects that have the same name as a already existing effects you will have to use the ID of the effect instead of the Name since that is the only way to uniquely identify the effect (the ID can easily be copied with the button shown in the image below).
I have also added a new feature that may be usefull to your specific use case "Self apply riding effects" which can be checked for a rider so that this rider will apply its own Riding effects when it mounts another token.
![image](https://github.com/Saibot393/Rideable/assets/137942782/43f8144e-b54f-4c57-a19c-ac71986146ee)
