### ISSUE TITLE
Tile riding function does not seem to work. Generates console errors

### ISSUE THREAD

**Issue by baileywick** [Saibot393/Rideable#36]
System: dnd5e 2.3.0
Foundry: v11 307 

I have a tile of an airship set to allow mounting when tokens enter its space. The token text indicates that the tokens have mounted the airship, but moving the tile does not move the tokens. It does generate the attached error.

![tile-settings](https://github.com/Saibot393/Rideable/assets/14203358/9c707517-ba91-4672-bd53-749cb452904e)
[dev.baileywikifoundry.world-1694913963734.log](https://github.com/Saibot393/Rideable/files/12641846/dev.baileywikifoundry.world-1694913963734.log)

**Comment by Saibot393** [comment]
I have just released v2.9.5 which should fix this issue. The problem was Wall-Height related, the module basically tried to calculate the Tiles Wall-Height Sight Elevation, which is of course doesn't make a lot of sense. 
I know that levels adds sort of a elevation for tiles, i am not quite sure yet how to translate that into a riding height.
