### ISSUE TITLE
Suggestion : Riding height can be automatically set if the Mount's height exists

### ISSUE THREAD

**Issue by franckflo** [Saibot393/Rideable#4]
I believe that the module Levels by TheRipper93 adds the setting  Token Height on the Identity tab of the Token Configuration: 

![image](https://github.com/Saibot393/Rideable/assets/80221412/ac645f67-4387-4b9b-997a-a20feb7d4aeb)

It would be nice if that could be used by rideable to set the rider's elevation when mounting, when that value has been set to something else than the default.

Another useful tweak would be the ability for the GM to adjust the rider's height manually while the token is riding, as the elevation seems stuck right now.

Thanks!

**Comment by Saibot393** [comment]
Thank you for your suggestions. 
I have looked into them, and i think both should be relatively easy to implement. I expect to add both features to v1.5.0 which i will probably release during the week.

**Comment by Saibot393** [comment]
Both features have been released with v1.5.0.
The first feature can be toggled via a setting that only shows up if the "Wall-Height" module is installed which should also be required for the "Level" module.
Since i dont know that much about either of the modules there is a higher chance of bugs or weird behaviour. Should you find any feel free to open an issue.
