### ISSUE TITLE
Weird error on console

### ISSUE THREAD

**Issue by Dyrnwyrm** [Saibot393/Rideable#49]
Before and after updating to 2.4 this error  error started popping on the console at random, i dont know why is happening and it does not affect the canvas per se, is just  a constant spam of errors on console.

![image](https://github.com/Saibot393/Rideable/assets/129613553/61bd5b59-0ec5-4f2e-837d-53f4e8fca566)

**Comment by Saibot393** [comment]
The bug (or atleast a very similar bug) can be recreated without rideable and only active auras. Put an active aura on a player controlled token, make sure that you as the GM are on another scene and let a player move the token:
![image](https://github.com/Saibot393/Rideable/assets/137942782/44c55886-d984-45aa-88da-466d5ce77997)

I therefore think that the bug is caused by active auras and Rideable just happens to trigger the update that results in the bug. I would assume, that there is a token in an inactive scene that somehow triggers an x y update.

To suppress the bug you could install [routinglib](https://foundryvtt.com/packages/routinglib) and set Rideables Following algorithm to "routinglib (advanced, resource heavy, recommended)".

I will leave this issue open for now and report the bug to active auras, should the active auras fix not solve the issue i will investigate further.

**Comment by Dyrnwyrm** [comment]
Sure ill test it, already have routinglib installed

**Comment by Dyrnwyrm** [comment]
Okay active auras fix and using routing lib fixes this issue seems like as you say was related to a token moven on a X Y update when the GM is not looking at the screen.

**Comment by Saibot393** [comment]
Good to hear
