### ISSUE TITLE
pf1e cannot get familiar riding to work

### ISSUE THREAD

**Issue by R0gu3P403n1x** [Saibot393/Rideable#64]
I am trying to get familiar riding to work.  
Foundry ver. 11.315
pf1e ver 9.6
rideable ver 2.19.5

The largest problem is no knowing how to make this function work.  I am using Party HUD and most of the controls are there, but not for companions.  When I try to use the Familiar Riding Macro as GM, nothing happens.  As a player it says "You do not have permission to execute Macro "Familiar Riding.""  I have enabled the players to be able to run script macros, so I am at a loss at this point.

I stripped all modules out except routing lib, rideable, and party HUD.  Same effects.  Removed Party HUD, same effect.  I am pretty sure I just don't know what I am doing, but I need help.

**Comment by Saibot393** [comment]
Do any errors show up in the console(F12)? Does the hotkey (default J) work?

**Comment by R0gu3P403n1x** [comment]
No errors, just nothing happens.

**Comment by Tarbarian** [comment]
@R0gu3P403n1x as I understand it the tag `game.Rideable.MountSelectedFamiliar(pTargetHovered)` only works in PF2e because that game system has an inbuilt familiar system. PF1e does not. You need a module to get proper familiar support in PF1e, which I presume this module doesn't integrate with. I ran into the same issue.

I write macro to resolve my issues though and I've made one and posted it here: [mountToggle](https://gitlab.com/tarbarian13/tarbarian-macros/-/blob/master/General/mountToggle.js?ref_type=heads)
Just set the rider and mount names as you'd like and use the dialog to mount/unmount the familiar as needed.

**Comment by Saibot393** [comment]
Sorry, i somewhat forgot about this issue, i just tested a bit and everythings seems to work fine for me, is the world setting "Familiar riding" enabled?

**Comment by Tarbarian** [comment]
Oh, it requires you to actually _target_ the "master." That makes sense, I just wasn't thinking about the actual targeting functionality. 

![FamiliarMounting](https://github.com/Saibot393/Rideable/assets/76751079/4b3d6e63-578d-4c9b-81eb-0dca7b1970cd)

I'm personally still going to stick with my macro for ease of use. Targeting can break the flow of play a bit.

**Comment by Saibot393** [comment]
Normally just hovering over the master token should be enough
